language: node_js
node_js:
  - stable
before_script:
  - yarn global add firebase-tools
script:
  - yarn build
before_deploy:
  - yarn deploy
deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "wc-redux-test"
